boson-project/buildpacks

- buildpacks/quarkus/bin/detect
this allows to recognize also quarkus-funqy-http extensions (for plain http)
> fix: make quarkus detection less restrictive

- stacks/ubi8-minimal/base/Dockerfile
- stacks/ubi8/base/Dockerfile
Red Hat product images will no longer be published with the 'latest' tag.
This commit pins our dependency to version 8.2.
Fixes: https://github.com/boson-project/buildpacks/issues/14
> stacks: change stack images to be built on UBI 8.2

- buildpacks/nodejs/runtime/package.json
- buildpacks/nodejs/runtime/server.js
This commit bumps the `@redhat/faas-js-runtime` dependency to v0.2.1.
> buildpacks(node): bump dependency on faas-js-runtime

- Makefile
Changes the various `pack` commands in the Makefile to no longer use deprecated (and removed in the latest version) flags for the `pack` CLI.
> build(pack): change deprecated/removed pack CLI flags

- buildpacks/nodejs/runtime/package.json
- buildpacks/nodejs/runtime/server.js
I'd like to run a new release of the buildpacks after this lands.
> Bump faas js runtime dependency

- buildpacks/nodejs/bin/detect
- buildpacks/quarkus/bin/detect
It is my understanding from the [buildpacks spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#detection) that a return code of 100 indicates the detection resulted in a negative detection, zero for a positive detection, and other numeric codes for exceptions/errors.  Therefore I believe these return codes should be 100.
> fix: return failure code for failed detection

- .github/workflows/ci.yaml
We have been bitten before by breaking changes in the pack CLI.
This commit fixes the version at 0.13.1 in CI.
Fixes: https://github.com/boson-project/buildpacks/issues/26
> chore: pin pack binary version at 0.13.1 in CI builds

- .github/workflows/ci.yaml
This should land before https://github.com/boson-project/buildpacks/pull/31
> chore(actions): bump release please to 2.4.1

- .github/workflows/ci.yaml
By default, the 2.x version of github's checkout action does not pull tags. Setting this configuration value forces it to.
See: https://github.com/actions/checkout/issues/338
> fix(actions): make sure checkout action pulls tags

- buildpacks/nodejs/runtime/package.json
- buildpacks/nodejs/runtime/server.js
The name of the module changed from `@redhat/faas-js-runtime` to `faas-js-runtime`
> chore(node): update faas-js-runtime with new name

- buildpacks/nodejs/runtime/package.json
@boson-project/core this is a hotfix for the dev preview release. The faas CLI templates assume faas-js-runtime >= 0.5.0 while the buildpack still installs 0.4.0. This fixes that. Given that most folks who would normally review this, I'm just going to land it and push a new release if the CI works - unless there is objection.
> fix(deps): sync node.js builder with faas CLI

- stacks/nodejs/build/Dockerfile
- stacks/nodejs/run/Dockerfile
This shaves about 30MB off of the run image sizes for Node.js
See: https://github.com/boson-project/buildpacks/issues/41
> fix: add --nodocs to dnf install to reduce image size

- buildpacks/go/bin/build
Fixes: https://github.com/boson-project/buildpacks/issues/40
> fix: don't assume /workspace in go builder

- .github/workflows/ci.yaml
For whatever reason, our CI was only running when commits landed on `master`. This change just ensures that it's run for pull requests as well. :exploding_head: 
> ci: ensure that the build is run on pull requests

- Makefile
- builders/go/builder.toml
- builders/nodejs/builder.toml
- builders/quarkus-jvm/builder.toml
- builders/quarkus-native/builder.toml
- builders/springboot/builder.toml
- buildpacks/go/buildpack.toml
- buildpacks/nodejs/buildpack.toml
- buildpacks/quarkus-jvm/buildpack.toml
- buildpacks/quarkus-native/buildpack.toml
- buildpacks/springboot/buildpack.toml
- stacks/build-stack.sh
Instead of using `com.redhat.faas`, these ids should be prefixed `dev.boson`.
Fixes: https://github.com/boson-project/buildpacks/issues/42
> fix: change buildpack, builder and stack ids

- Makefile
- builders/python/builder.toml
- buildpacks/python/bin/build
- buildpacks/python/bin/detect
- buildpacks/python/buildpack.toml
- buildpacks/python/lib/build.sh
- buildpacks/python/runtime/server.py
- packages/python/package.toml
- stacks/nodejs/build/nodejs.module
- stacks/nodejs/run/nodejs.module
- stacks/python/build/Dockerfile
- stacks/python/build/python.module
- stacks/python/run/Dockerfile
- stacks/python/run/python.module
- stacks/ubi8/base/Dockerfile
This commit adds a python buildpack and simple invoker. This is awork in progress. Existing issues:
- Extremely slow on first build (>10 minutes) subsequent builds are really quick
- Attempt to install python 3.8 on UBI images results in 3.6?
- The installed pip is very old
- ~No user dependencies capability yet~
- ~Only CloudEvents functions are supported at the moment~
- ~Still needs a production runtime - at the moment, it's development mode only~
> src(buildpack): add python

- .github/workflows/ci.yaml
I was going to cut a new release for Python, and realized that release please has not been running. I have no idea if it will pick up the changes from the Python additions. If not, we will need to create a manual release.
> chore: update CI branch to use main

- buildpacks/nodejs/runtime/server.js
This PR adds support for a `FUNCTION_LOG_LEVEL` environment variable. This can be used to enable the log level after this PR is merged in the Node.js FaaS runtime: https://github.com/boson-project/faas-js-runtime/pull/82/files
> feat: support configurable log levels for node.js functions

- stacks/quarkus-native/build/Dockerfile
This is required for Quarkus 1.13
> chore: update GraalVM to 21

- buildpacks/nodejs/runtime/package.json
Just noticed I missed this requirement in my original PR. Sorry about that @lance !
> fix: bump nodejs faas runtime dependency for log levels

- Makefile
- builders/nodejs/builder.toml
- buildpacks/nodejs/lib/build.sh
- buildpacks/nodejs/runtime/package.json
- buildpacks/nodejs/runtime/server.js
- buildpacks/typescript/bin/build
- buildpacks/typescript/bin/detect
- buildpacks/typescript/buildpack.toml
- packages/typescript/package.toml
- stacks/nodejs/build/Dockerfile
- stacks/python/build/Dockerfile
- stacks/python/build/python.module
- stacks/python/run/Dockerfile
- stacks/python/run/python.module
- stacks/quarkus-native/build/Dockerfile
- stacks/ubi8-minimal/base/Dockerfile
- stacks/ubi8/base/Dockerfile
This commit adds support for TypeScript in the Node.js builder image by
providing a new typescript buildpack.
It does not create a new builder and/or stack, as it can just reuse the
Node.js stack and builder images.
These changes require a dependency on currently unreleased code in the
faas-js-runtime framework, so the Node.js and TypeScript templates have
been updated to depend on a github hash version of that for now. This will
need to change ultimately.
The dependency on a github hash required updates to the base image, since
it does not include the git binary by default. That has been added to the
base node.js build image.
Additionally, stacks have been bumped to be based on ubi[-minimal] 8.4.
> feat: add support for typescript projects in nodejs builder

- buildpacks/nodejs/runtime/server.js
Seehttps://github.com/boson-project/faas-js-runtime/pull/94#discussion_r636906116
> fix: use FUNC_* as environment prefix in Node apps

- builders/nodejs/builder.toml
Makes the node builder work for node projects again.
> fix: make typescript optional for Node builds

- stacks/go/build/Dockerfile
- stacks/go/run/Dockerfile
- stacks/nodejs/build/Dockerfile
- stacks/nodejs/run/Dockerfile
- stacks/python/build/Dockerfile
- stacks/python/run/Dockerfile
- stacks/quarkus-native/build/Dockerfile
- stacks/quarkus-native/run/Dockerfile
- stacks/ubi8-minimal/base/Dockerfile
- stacks/ubi8/base/Dockerfile
Almost all of the Dockerfiles were doing things like setting the HOME
env var to an unused directory, and configuring the cnb user. Anything
that is still needed (not unsed) and common, has been moved to the base
ubi images for the stacks.
> chore(refactor): remove duplicated code in stack dockerfiles

- Makefile
- builders/go/builder.toml
- builders/jvm/builder.toml
- builders/nodejs/builder.toml
- builders/python/builder.toml
- builders/quarkus-native/builder.toml
Changes commands in Makefile to their current, non-deprecated style. Also
changes the `image` key in builder.toml to `uri`, using a fully qualified
`docker://` uri for the value.
> chore: stop using deprecated pack commands

- buildpacks/nodejs/bin/build
- buildpacks/nodejs/lib/build.sh
- buildpacks/nodejs/runtime/package-lock.json
Previously the build phase would only install the invoker once. After this,
if /workspace/.invoker directory was found, it would just assume the invoker
was already there and skip it.
A case where this could be a problem is if the invoker has been updated in
the buildpack. Functions that have previously been built will skip installation
of the new invoker.
This change modifies the behavior so that the invoker itself is always installed.
This is no problem with build time. It just copies two files. Then the
package-lock.json checksum is used to determine if there has been a change,
and if so, run npm ci again.
> fix: improve caching for invoker and main path discovery

- Makefile
- builders/rust/builder.toml
- buildpacks/rust/bin/build
- buildpacks/rust/bin/detect
- buildpacks/rust/buildpack.toml
- packages/rust/package.toml
- stacks/rust/build/Dockerfile
- stacks/rust/run/Dockerfile
A pretty simple first attempt here, using the cargo/rust packages available in the Red Hat ubi repo (rustc v1.49.0)
Possible enhancements include rust version selection using `rustup` and non-linked binaries using a musl target.
> Add buildpack/builder/stacks for Rust

- buildpacks/go/bin/build
- buildpacks/nodejs/bin/build
- buildpacks/nodejs/lib/build.sh
- buildpacks/python/bin/build
- buildpacks/quarkus-jvm/bin/build
- buildpacks/quarkus-native/bin/build
- buildpacks/rust/bin/build
- buildpacks/springboot/bin/build
This commit removes all instances of func.yaml from a built image.
In doing this, I also refactored the Node.js buildpack so that the app
is no longer running from the /workspace build directory. Instead, it's
run from a layer at /layers/app.
Fixes: https://github.com/boson-project/buildpacks/issues/87
> refactor: remove func.yaml from all run images

- buildpacks/go/bin/detect
- buildpacks/nodejs/bin/detect
- buildpacks/python/bin/detect
- buildpacks/quarkus-jvm/bin/detect
- buildpacks/quarkus-native/bin/detect
- buildpacks/rust/bin/detect
- buildpacks/springboot/bin/detect
Only projects containing func.yaml should evaluate as true during the buildpack detect phase.
> src: update all buildpacks to only handle functions

- .github/workflows/ci.yaml
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
Fixes: #113
> chore: access `secrets.GITHUB_TOKEN` only on `main` branch

- buildpacks/nodejs/bin/build
- buildpacks/nodejs/runtime/package-lock.json
- buildpacks/nodejs/runtime/package.json
- buildpacks/nodejs/runtime/server.js
This allows the function buildpack to use func.yaml for specifying
logLevel, and potentially other values in the future.
See: https://github.com/boson-project/faas-js-runtime/pull/104
See: https://github.com/knative-sandbox/kn-plugin-func/pull/462
> feat: support for `options.config` on server start

- builders/go/builder.toml
- builders/jvm/builder.toml
- builders/nodejs/builder.toml
- builders/python/builder.toml
- builders/quarkus-native/builder.toml
- builders/rust/builder.toml
Fixes issues with podman/systemd closing connection.
Using lifecycle: github.com/matejvasek/lifecycle/tree/v0.13.0-patched
https://github.com/matejvasek/lifecycle/commit/67952bfdf0576a19f36d9df592626f0341fd38e7
> fix: use patched lifecycle

- test/test_builders.go
We need to read all of the `docker image inspect` output.
> test: fix test freezes
